### ISSUE TITLE
SVG < ie9 support

### ISSUE THREAD

**Issue by willforsyth** [sambeckham/pattern-library-template#24]
I am adding a new way to handle the SVGs. What are your thoughts on adding in ie8 support and below as default.

**Comment by willforsyth** [comment]
I have added it in for the time being, its easier to remove than have to add in.

**Comment by sambeckham** [comment]
No, we only support IE9+ there's too much bloat otherwise for an outdated browser

**Comment by willforsyth** [comment]
I was inclined to go towards that from the outset, with the way clients work at the moment not sure when this will be reality, however its easy enough to add back in. I will remove it from the pull request. Makes this a cleaner start for users. Can always leave instructions in the future for users who want to add in < ie9.
