### ISSUE TITLE
Font Support

### ISSUE THREAD

**Issue by willforsyth** [sambeckham/pattern-library-template#27]
Shall we add in font support as default? So adding the folder into the build process and into the serve process.

**Comment by sambeckham** [comment]
What do you mean by Font support?

**Comment by willforsyth** [comment]
Support for fonts hosted in fonts directory ( font-face ). So adding the folder into the build process and into the serve process. Just means adding in bit more to grunt copy etc.

**Comment by sambeckham** [comment]
Might not be a bad shout, Shouldn't be too much of a change

**Comment by sambeckham** [comment]
https://github.com/christiannaths/Redacted-Font

**Comment by willforsyth** [comment]
Redacted font has been added along with support
